

[uwsgi]
# Module Python à charger
module = nom_de_votre_projet.wsgi:application

# Chemin vers votre projet Django
chdir = /chemin/vers/votre/projet

# Fichier de socket pour communiquer avec le serveur web
socket = /chemin/vers/votre/projet/nom_de_votre_projet.sock

# Nombre de processus uWSGI à démarrer
processes = 4

# Démarrer le serveur HTTP intégré à uWSGI
http-socket = :8000

# Activer le mode de démon
daemonize = /chemin/vers/le/fichier/de/logs/uwsgi.log
